Добавлены обработчики событий для управления размером и фильтрами загружаемого изображения, выполнена валидация поля ввода хэштегов
htmlacademy-javascript/1476617-kekstagram-21 pull request #4
Opened 2020-10-11 20:35 UTC by Kirshach

2020-10-11 20:44 UTC, Kirshach commented
Дичайше извиняюсь за хаос в коде, надеюсь, следующая тема предоставит возможность причесать его 😅

2020-10-12 06:47 UTC, 4err requested changes
Трэвис!

https://take.ms/VLiCS Цифры меняются, а масштаб изображения нет.

Клик на ползунке не работает и не меняет эффект.

2020-10-12 06:47 UTC, 4err commented on js/main.js
> +  setTimeout(() => {
Зачем таймаут?

2020-10-12 06:47 UTC, 4err commented on js/main.js
> +    scaleValue.value = `${Math.max(parseInt(scaleValue.value, 10) - 25, 25)}%`;
Ну магические же числа :(

2020-10-12 06:47 UTC, 4err commented on js/main.js
> +  }
Интересный подход с датасетом. Хотя на самом деле, т.к. у нас у изображения единовременно содержится только один класс, можно просто очищать списко классов через `.classList = ""` 

Не нужно убирать свое решение, это просто заметка.

2020-10-12 18:25 UTC, Kirshach commented on js/main.js
> +  }
Подумал "а что если будует ещё"...

2020-10-12 18:38 UTC, Kirshach commented
- Не удовлетворил трэвиса потому что пока не понял, не понадобятся ли в ближайшее время функции генерации мокапов, написанные для тестирования фуллскрин-режима
- Ползунку пока не добавлял интерактивность т.к. в задании было сказано, что мы займёмся этим позже: решил, что, возможно, сейчас сделаю это неоптимально

2020-10-13 05:44 UTC, 4err requested changes
https://take.ms/kunWq По заданию нужно реализовать изменение уровня фильтра посредством отпускания мыши. 

Чтобы удовлетворить тревис ты можешь закомментировать участки кода на которые он ругается.

2020-10-13 05:44 UTC, 4err commented on js/main.js
> +const MIN_SCALE = 25;
Константы должны быть определены в начале файла.

2020-11-01 07:59 UTC, merged